export const mockData = [
  {
    id: 1,
    imgSrc: 'src/assets/home-page-img.png',
    title: 'Cheeseburger',
    doughTypes: ['thin', 'traditional'],
    price: 420,
    sizes: [35, 45, 55],
  },
  {
    id: 2,
    imgSrc: 'src/assets/home-page-img.png',
    title: 'Chicken',
    doughTypes: ['thin', 'traditional'],
    price: 320,
    sizes: [35, 45, 55],
  },
  {
    id: 3,
    imgSrc: 'src/assets/home-page-img.png',
    title: 'Asian',
    doughTypes: ['thin', 'traditional'],
    price: 120,
    sizes: [35, 45, 55],
  },
  {
    id: 4,
    imgSrc: 'src/assets/home-page-img.png',
    title: 'Cheese',
    doughTypes: ['thin', 'traditional'],
    price: 420,
    sizes: [35, 45, 55],
  },
  {
    id: 11,
    imgSrc: 'src/assets/home-page-img.png',
    title: 'Cheeseburger',
    doughTypes: ['thin', 'traditional'],
    price: 420,
    sizes: [35, 45, 55],
  },
  {
    id: 12,
    imgSrc: 'src/assets/home-page-img.png',
    title: 'Chicken',
    doughTypes: ['thin', 'traditional'],
    price: 320,
    sizes: [35, 45, 55],
  },
  {
    id: 13,
    imgSrc: 'src/assets/home-page-img.png',
    title: 'Asian',
    doughTypes: ['thin', 'traditional'],
    price: 120,
    sizes: [35, 45, 55],
  },
  {
    id: 14,
    imgSrc: 'src/assets/home-page-img.png',
    title: 'Cheese',
    doughTypes: ['thin', 'traditional'],
    price: 420,
    sizes: [35, 45, 55],
  },
];
